### ISSUE TITLE
🚀[FEA]: Extending Diagnostic Models to take files as inputs/Being able to work with Ensembles

### ISSUE THREAD

**Issue by david5010** [NVIDIA/earth2studio#132]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem you would like to solve.

Hi,

I've enjoyed the Earth2Studio framework so far (seems to be better than Earth2MIP from experience). One interesting use case that I'm encountering is the analysis of cyclones/AR. ClimateNet originally intakes .nc files (converts them to a custom dataset) and analyzes them. The current workflow in Earth2Studio is all together, and if I'm not mistaken you have to give the Prognostic model rather than being able to use the file. It would be a great addition if we do diagnostic on ensembles (getting potential cyclone tracks...etc.)

**Comment by NickGeneva** [comment]
Hi @david5010 

If I'm understanding you correctly, you're looking to feed data directly from a file into ClimateNet?

The diagnostics can be worked with directly rather than using the coupled workflow you're referencing. The [interface](https://nvidia.github.io/earth2studio/userguide/components/diagnostic.html#diagnostic-interface) for each takes in a tensor and a coordinate system, so if you have some data on disk you can:

- either use the built in Xarray datasets or develop your own to read from the files you have
- use the `fetch_data` util to then generate the tensor and coordinate system
- feed this into the ClimateNet model directly and get the outputs

This will be writing your own workflow, but this is what we want users to do. Have a look at the corrdiff example for a reference on directly working with a diagnostic: https://nvidia.github.io/earth2studio/examples/04_corrdiff_inference.html#sphx-glr-examples-04-corrdiff-inference-py

**Comment by NickGeneva** [comment]
Sounds good, IO is one of the more complicated parts... largely due to saving the meta data (coordinate systems) in a meaningful way but not the data itself! Definitely look at existing samples and [docs](https://nvidia.github.io/earth2studio/userguide/components/io.html) to better understand how we go about doing things.

Alternatively, you can always skip IO and save things yourself manually however you'd like. Its all just tensors and dictionaries at the end of the day : )

**Comment by david5010** [comment]
Thank you! I spent quite some time today analyzing the code and it seems that I'm getting confused on NetCDFBackend and XarrayBackend. I'm assuming that the xr.py for datasource is meant to work with XarrayBackend. I'll try to follow closely to some of the run.py example to see if I'm understanding things better. Thank you again for all the help!

**Comment by david5010** [comment]
@NickGeneva Thank you! I'm still trying it out but running into quite a few issues (might be my lack of understanding).

1. I don't fully understand the xr.py (DatasetFile) specifically. I tried loading the ensemble into DatasetFile but I'm a bit confused on the array_name. I've tried a single variable to a list of variable but it doesn't seem to fully work. 

I might experiment more or try a hybrid version of ensemble and the diagnostic workflow

**Comment by david5010** [comment]
Oh I see, so it's simply a place holder until the data source is called again, right?

**Comment by NickGeneva** [comment]
You are correct the implementation in Earth2Studio expects variable to be a coordinate in the array.

If you want to keep your data how it is now. I would recommend writing your own that works for this data format. As long as you expose the expected data source [interface](https://nvidia.github.io/earth2studio/userguide/components/datasources.html#data-source-interface) then it will work.


Something along the lines of:
```
def __call__(
        self,
        time: datetime | list[datetime] | TimeArray,
        variable: str | list[str] | VariableArray,
    ) -> xr.DataArray:
 
  arrays = []
  for var in variable:
      da = self.dataset[var].isel(ensemble=0, lead_time=0).sel(time=time)
     # Will need to add a var dim to data and variable coord system
     da = da.assign_coords(variable=[var])
     da = da.expand_dims(dim={"variable": 1}, axis=1)
     arrays.append(da)

  return xr.concat(arrays, dim='variable')
```

**Comment by david5010** [comment]
@NickGeneva Hi,

I still couldn't get it to work by mimicking built-in workflows so I tried to work directly with the tensors as you suggested. I reformatted by ensemble forecast into tensors that ClimateNet takes (shape (batch, variables, lat, lon) where variables are ordered = ["tcwv", "u850", "v850", "msl"] and gave the climatenet input coords). The issue now is that everything shows up as nan. I checked the scaling and got some really high values 1e36...etc. Could it be that ClimateNet doesn't take that ordering?

**Comment by NickGeneva** [comment]
Climate should take those variables based on the [code](https://github.com/NVIDIA/earth2studio/blob/main/earth2studio/models/dx/climatenet.py#L34). Is your input data normalized at all? The model will normalize / de-normalize the values for [you](https://github.com/NVIDIA/earth2studio/blob/main/earth2studio/models/dx/climatenet.py#L172).

Also to confirm, I'm assuming that the model loaded successfully from the default package as well?

**Comment by david5010** [comment]
@NickGeneva I don't think the values were normalized since I saw that the function normalizes inside. However, I did notice a possibility for the nan output.

I first forecasted FCN using Spherical Gaussian as an ensemble for the variables "tcwv", "u850", "v850" and "msl". I did notice that for some reason, I have extreme values at some point:

[1.00369484e+05, 1.00360547e+05, 1.00354516e+05, ...,
           1.00358773e+05, 1.00379492e+05, 1.00367367e+05],
          [9.96920997e+36, 9.96920997e+36, 9.96920997e+36, ...,
           9.96920997e+36, 9.96920997e+36, 9.96920997e+36]]]]],

I don't know if this is a common issue. I used the built-in ensemble workflow too.

**Comment by NickGeneva** [comment]
@david5010 fcnv2 small is an older version of SFNO thats smaller and fine tuned to deterministic accuracy. SFNO is the same architecture as FCN V2 that we have seem better performance for ensembling with... but I leave the full assessment up to you. Thanks!

**Comment by david5010** [comment]
@NickGeneva Interesting enough, it seems that SFNO didn't perform as well as FCNV2 from earth2mip for cyclone analysis. When applying ClimateNet, SFNO results showed a lot of noise. But I do think there might be other factors at play like how I set the perturbation for SFNO...etc.
