### ISSUE TITLE
🐛[BUG]: Omegaconf missing from install for stormcast

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2studio#172]
### Version

0.5.0a

### On which installation method(s) does this occur?

Source

### Describe the issue

Do we need a storm cast specific install, remove the need for omega conf or put it part of core install?

**Comment by pzharrington** [comment]
@NickGeneva For my own understanding, did this get through CI bc we run CI with the modulus container (which has omegaconf?)

**Comment by NickGeneva** [comment]
Yep exactly!

**Comment by pzharrington** [comment]
K. Are you opposed to just adding `omegaconf` as a core dependency for now? Alternately we could swap the StormCast NGC package loading to json, which would require updating the public NGC package to use a json instead of yaml to store the model config -- maybe we wait until Dallas is back to do that?
